FROM maven:3.8.3-openjdk-17 as builder
COPY  . /opt/maven
WORKDIR /opt/maven
RUN mvn install

FROM gcr.io/distroless/java17-debian11:debug
COPY  --from=builder /opt/maven/target /app/target
WORKDIR /app
EXPOSE 8080
SHELL ["/busybox/sh", "-c"]
RUN adduser beer -D
USER beer

CMD ["target/craftbeer-0.0.1-SNAPSHOT.jar"]